### ISSUE TITLE
Taxon Bacteria id 2 is not submittable.

### ISSUE THREAD

**Issue by tillrobin** [EBI-Metagenomics/genome_uploader#1]
Hello,
I got this error with the taxonomic assignment. Non of the MAGs have only TaxID 2.

python genome_upload.py -u $UPLOAD_STUDY --genome_info iMGMC-MAG-metaDATA-Munich.tab --mags --xmls --manifests --webin $WEBIN_ID --password $myPASSWORD --out iMGMC-data-Munich --centre_name "$centre_name"

File used for metadata:
https://drive.google.com/file/d/17c6tun_zzwpUedkpvvKONfk7V7B5BEhq/view?usp=share_link

Warning: genome submission is not in live mode, files will be validated, but not uploaded.
Retrieving data for MAG submission...
	Retrieving info for genomes to submit...
	Retrieving project and run info from ENA (this might take a while)...
	A backup file has been found.
	Writing genome registration XML...
	All files have been written in iMGMC-data-Munich/MAG_upload
registered_MAGs_test.tsv
Registering genome samples XMLs...
	Registering sample xml in test mode.
	Genomes could not be submitted to ENA. Please, check the errors below.
	In sample, alias: "single-Munich_Cecal.52_1673343261". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.81_1673343264". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.89_1673343265". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.99_1673343267". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.101_1673343269". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.104_1673343271". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.139_1673343274". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.162_1673343277". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Cecal.163_1673343278". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.1_1673343279". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.2_1673343280". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.48_1673343282". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.139_1673343290". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.157_1673343292". Taxon Bacteria id 2 is not submittable.
	In sample, alias: "single-Munich_Feces.175_1673343293". Taxon Bacteria id 2 is not submittable.

Best Till Robin

**Comment by tillrobin** [comment]
In addition:
After removing this MAGs I got another error:

Warning: genome submission is not in live mode, files will be validated, but not uploaded.
Retrieving data for MAG submission...
        Retrieving info for genomes to submit...
        Retrieving project and run info from ENA (this might take a while)...
        Writing genome registration XML...
        All files have been written in iMGMC-data-Munich-error/MAG_upload
registered_MAGs_test.tsv
Registering genome samples XMLs...
        Registering sample xml in test mode.
        129 genome samples successfully registered.
Generating manifest files...
Traceback (most recent call last):
  File "/vol/projects/trlesker/genome_uploader/genome_upload.py", line 1243, in <module>
    choose_methods()
  File "/vol/projects/trlesker/genome_uploader/genome_upload.py", line 1202, in choose_methods
    manifestInfo = compute_manifests(ENA_uploader, genomes, samples_xml)
  File "/vol/projects/trlesker/genome_uploader/genome_upload.py", line 928, in compute_manifests
    genomes[g]["alias"], genomes[g]["assembler"], genomes[g]["sequencingMethod"],
KeyError: 'assembler'

**Comment by Ge94** [comment]
Hi Till, 
Thank you for your interest. I just committed a bug fix that should cover both problems. Please, let me know if encounter any other issue. 

Best
