### ISSUE TITLE
genome_upload.py is not available

### ISSUE THREAD

**Issue by ay-amityadav** [EBI-Metagenomics/genome_uploader#17]
Hi,

I installed genome_uploader using the below two commands:
```
conda env create -f requirements.yml
conda activate genome_uploader
```

When trying to run  `python genome_upload.py ...` , it says no such file is present. I checked the genome_uploader path directory, and indeed `genome_upload.py` is not there. 

Can you please see this?

Many thanks
Amit

**Comment by Ge94** [comment]
Hi Amit, thank you for reporting this! We haven't updated the documentation yet - the project has been restructured and the main script is in another location now. More specifically, you will need to run `python genomeuploader/genome_upload.py ...`. As an alternative you could add the full path to `genome_upload.py` to your $PATH environment variable. 

Thank you
Germana
