### ISSUE TITLE
What should I do if I don't have genome coverage?

### ISSUE THREAD

**Issue by SilasK** [EBI-Metagenomics/genome_uploader#2]
The genome coverage depends on the sample it is quantified. What should I put in if I don't have the coverage from the original sample?

**Comment by Ge94** [comment]
Hi Silas, 
You should be able to compute genome coverage by aligning raw reads against each genome (e.g. with tools like bwa, bowtie2, BBMap...) and then extract coverage information with tools like samtools or BEDtools. As an alternative, some binners like metabat already generate this statistics in-house, therefore it is enough to retrie

**Comment by SilasK** [comment]
I don't have the original samples anymore and didn't kept the internal files from metabat. I didn't found this information relevant to keep. as the coverage will be different in each sample..

**Comment by Ge94** [comment]
Hi Silas, 
According to ENA guidelines, the preferred behaviour would be to have raw reads associated to genome assemblies. I know you are currently in contact with a colleague of mine about this, she is trying to sort this out with ENA helpdesk. As your case is quite exceptional, and it is unrelated to the scripts usage, I will close this issue and let my colleague work on this.
