### ISSUE TITLE
How to put multiple run accession

### ISSUE THREAD

**Issue by SilasK** [EBI-Metagenomics/genome_uploader#3]
When I assemble MAGs I take all the runs from the same biosample. As these represent often different lanes or different sequencing runs of the same sample. How can I fill in these in the column run_accessions ? e.g. can I separate them by a comma?

**Comment by Ge94** [comment]
Hi Silas, 
Yes, if multiple runs were used to generate the genome, they should be listed as comma-separated in the run_accessions column. I will add this to the documentation.
